version: '3'

networks:
    pwt:
services:
    apache:
        image: php:7.4-apache
        container_name: ApacheWebServer
        ports:
            - "8080:80"
        volumes:
            - ./:var/www/html
        depends_on:
            - mysql
        networks:
            - pwt
    mysql:
        image: mysql:5.7.30
        container_name: MySQLDatabase
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - pwt
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
            SERVICE_TAG: dev
            SERVICE_NAME: mysql
